#!/bin/bash

 sxhkd & 

wmname LG3D &

###---Rules---### 
bspc rule -r '*'
###---Rules---### 

###---Autostart---###
killall polybar
~/.config/polybar/launch &
# killall "tint2"
# tint2 &
# xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)
killall "nm-applet" 
nm-applet &
killall "dropbox" 
dropbox start &
# emacsclient -n -create-frame --alternate-editor="" &
###---Autostart---### 


bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9


bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner 
bspc config click-to-focus none 

bspc config focus_follows_pointer true


bspc config border_width         1
bspc config window_gap 			 0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

bspc config ignore_ewmh_focus true # prevents focus from being stolen 

###---Border Colours---### 

##--Pywal custom
# source the colors.
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

##--Previous custom
# bspc config normal_border_color "#0000FF"
# bspc config active_border_color "#FF0000"
# bspc config focused_border_color "#00FF00"

###---Border Colours---###



###---Placement of Windows---###  
bspc config top_padding 22      # adding top padding to allow for polybar to show
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
###---Placement of Windows---###



###---Monitors---###
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true 
###---Monitors---###

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off



