;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-forward-char
        evil-forward-word-begin
        evil-previous-line
        hungry-delete-backward
        ))

(setq mc/cmds-to-run-once
      '(
        evil-insert
        evil-next-line
        ))
