;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-delete-forward
        c-electric-paren
        c-electric-star
        c-indent-line-or-region
        dabbrev-expand
        dumb-jump-go
        electric-pair-delete-pair
        emmet-expand-line
        end-of-visual-line
        forward-sentence
        gdscript-indent-dedent-line-backspace
        handle-switch-frame
        hungry-delete-backward
        hungry-delete-forward
        keyboard-escape-quit
        kill-region
        kill-visual-line
        my-insert-tab-char
        org-agenda-show-and-scroll-up
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-forward-sentence
        org-self-insert-command
        overwrite-mode
        set-fill-column
        slime-autodoc-space
        text-scale-adjust
        toggle-input-method
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        smex
        ))
